### ISSUE TITLE
NZXT Aer RGB & HUE+

### ISSUE THREAD

**Issue by catamphetamine** [0x7fffffff/Hackintosh#1]
So, how do the Aers work under macOS (os x)?
Did you boot up Windows and configure them using NZXT tool and then rebooted into Hackintosh and it still kept the preset even after restarting?

**Comment by mickmaccallum** [comment]
@catamphetamine Exactly correct. You have to configure them on Windows and the settings will persist when you boot macOS. The settings will persist unless there is a power failure, in which case, you have to boot Windows and reconfigure.

**Comment by catamphetamine** [comment]
Cool, thx.
I guess the controller stores the preset in its RAM then, if power outage or cable disconnection clears it.
